
	SUBROUTINE PERIOD_HELP (COMMAND)

C=============================================================================
C Routine to provide on-line help for PERIOD. 
C
C Written by Vikram Singh Dhillon @LPO 17-March-1993.
C=============================================================================

	IMPLICIT NONE

C-----------------------------------------------------------------------------
C PERIOD_HELP declarations.
C-----------------------------------------------------------------------------

	INTEGER I, ILEN, ILEN2
	LOGICAL PERIOD_PARSE
	CHARACTER*12 COMMAND
	CHARACTER*72 STRING
	CHARACTER*100 FILENAME, HELP_DIR

C-----------------------------------------------------------------------------
C Determine value of PERIOD_HELP environment variable using the f77 intrinsic
C function GETENV.
C-----------------------------------------------------------------------------

      CALL GETENV ('PERIOD_HELP', STRING)
      DO ILEN = 1, 100
         IF (STRING(ILEN:ILEN) .EQ. ' ') THEN
            GOTO 5            
         END IF
      END DO
5     HELP_DIR = STRING(1:ILEN-1)

C-----------------------------------------------------------------------------
C Help information.
C-----------------------------------------------------------------------------

	IF( PERIOD_PARSE( COMMAND, 'HELP')       ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_help.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=10)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
10	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP INPUT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_input.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=20)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
20	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP NOISE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_noise.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=30)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
30	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP WINDOW') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_window.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=40)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
40	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP FAKE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_fake.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=50)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
50	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP DETREND') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_detrend.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=60)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
60	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP SINE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_sine.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=70)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
70	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP FOLD') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_fold.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=80)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
80	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP HELP') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_help.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=90)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
90	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP QUIT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_quit.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=100)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
100	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP FIT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_fit.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=110)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
110	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP OPEN') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_open.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=120)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
120	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP CLOSE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_close.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=130)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
130	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP PERIOD') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_period.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=140)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
140	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP PLT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_plt.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=150)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
150	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP SHOW') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_show.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=160)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
160	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP OUTPUT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_output.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=170)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
170	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP SELECT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_select.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=180)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
180	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP FREQ') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_freq.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=190)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
190	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP CHISQ') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_chisq.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=200)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
200	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP FT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_ft.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=210)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
210	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP SCARGLE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_scargle.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=220)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
220	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP CLEAN') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_clean.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=230)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
230	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP STRING') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_string.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=240)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
240	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP PDM') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_pdm.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=250)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
250	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP PEAKS') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_peaks.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=260)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
260	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP SIG') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_sig.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=270)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
270	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP UINPUT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_uinput.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=280)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
280	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP USLOTS') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_uslots.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=290)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
290	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP EXIT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_quit.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=300)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
300	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP ARITH') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_arith.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=310)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
310	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP CLIP') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_clip.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=320)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
320	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP OVERPLOT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_overplot.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=330)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
330	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP OFF') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_off.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=340)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
340	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP QDP') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_qdp.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=350)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
350	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP SMOOTH') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_smooth.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=360)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
360	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP BIN') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_bin.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=370)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
370	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP INTEG') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_integ.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=380)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
380	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP COPY') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_copy.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=390)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
390	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP DEL') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_del.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=400)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
400	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP APPEND') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_append.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=410)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
410	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP TIME') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_time.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=420)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
420	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

  	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP BASE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_base.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=430)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
430	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

 	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP AMPLITUDE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_amplitude.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=440)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
440	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

    	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP SLIDE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_slide.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=450)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
450	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

    	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP AIRMASS') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_airmass.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=460)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
460	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

    	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP BOOT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_boot.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=470)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
470	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

    	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP DERIV') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_deriv.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=480)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
480	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

    	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP ERRORS') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_errors.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=490)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
490	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

    	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP HIST') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_hist.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=500)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
500	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999
	
    	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP JIGGLE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_jiggle.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=510)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
510	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP POLY') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_poly.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=520)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
520	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP UCAL') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_ucal.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=530)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
530	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP UNBLUE') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_unblue.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=540)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
540	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP XCOR') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_xcor.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=550)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
550	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP HINPUT') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_hinput.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=560)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
560	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999

	ELSE IF( PERIOD_PARSE( COMMAND, 'HELP HSLOTS') ) THEN
	WRITE(FILENAME,'(A)')HELP_DIR
	WRITE(FILENAME(ILEN:),'(A)')'/period_hslots.hlp'
	DO ILEN2 = 1, 100
	IF (FILENAME(ILEN2:ILEN2) .EQ. ' ') THEN	      
	OPEN (UNIT=10, FILE=FILENAME(1:ILEN2), STATUS='OLD', ERR=570)
	END IF
	END DO
	DO I = 1, 1000000000
	READ(10,'(A)',END=999)STRING
	WRITE(*,*)STRING
	END DO
570	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: Could not open file ',FILENAME(1:ILEN2)
	GOTO 999
		
	ELSE 
	WRITE(*,*)ACHAR(7)
	WRITE(*,*)'** ERROR: HELP command not recognised = ',COMMAND
	WRITE(*,*)' '
	RETURN
	END IF
999	CLOSE (UNIT=10)
	WRITE(*,*)' '
	RETURN
	END
